# Generated by Django 2.1.7 on 2019-08-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_profile_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
