# Generated by Django 2.2.4 on 2019-08-03 17:51

from django.db import migrations, models
import myproject.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, storage=myproject.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
