# Generated by Django 2.1.7 on 2019-08-01 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190801_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
