# Generated by Django 2.1.7 on 2019-08-02 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_like',
        ),
        migrations.AddField(
            model_name='post',
            name='user_like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
